version: 2.1

orbs:
  docker: circleci/docker@1.0.1

workflows:
  build_and_push_dev:
    jobs:
      - docker/publish:
          dockerfile: docker/tekstaro.dockerfile
          image: iocarney/tekstaro_dev
          path: ./
  build_and_push_aws:
    jobs:
      - docker/publish:
          dockerfile: docker/aws.dockerfile
          image: iocarney/tekstaro_aws
          path: ./
