version: 2.1

orbs:
  docker1: circleci/docker@1.0.1
  docker2: circleci/docker@1.0.1

jobs:
  login:
    docker:  # run the steps with Docker
      - image: circleci/elixir:1.9.4  # ...with this image as the primary container; this is where all `steps` will run
    steps:
      - run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_LOGIN --password-stdin


workflows:
  version: 2
  build_and_push:
    jobs:
      - docker1/publish:
          dockerfile: docker/tekstaro.dockerfile
          image: iocarney/tekstaro_dev
          path: ./
      - login:
          requires:
            - docker1/publish
      - docker2/publish:
          requires:
            - login
          dockerfile: docker/aws.dockerfile
          image: iocarney/tekstaro_aws
          path: ./
