version: 2.1

orbs:
  docker: circleci/docker@1.0.1

workflows:
  build_and_push:
    jobs:
      - docker/publish:
          dockerfile: docker/tekstaro.dockerfile:$TAG
          image: iocarney/tekstaro_dev
          path: ./

      - docker/publish:
          dockerfile: docker/aws.dockerfile
          image: iocarney/tekstaro_aws:$TAG
          path: ./
