version: 2.1

orbs:
  docker: circleci/docker@1.0.1

workflows:
  build_and_push_dev:
    jobs:
      - docker/build:
          dockerfile: docker/tekstaro.dockerfile
          image: iocarney/tekstaro_dev
          path: ./
      - docker/publish:
          requires:
            - build_and_push_dev
          dockerfile: docker/aws.dockerfile
          image: iocarney/tekstaro_aws
          path: ./
