version: 2.1

orbs:
  docker: cricleci/docker@1.0.1

workflows:
  build_and_push:
    jobs:
      - docker/publish:
          dockefile: docker/tekstaro.dockerfile
          image: tekstaro/tekstaro_release
          path: ./
          registry: hub.docker.com
