version: 2.1

orbs:
  docker: cricleci/docker@1.0.1

jobs:  # basic units of work in a run
  build_and_push:
    dockefile: docker/tekstaro.dockerfile
    image: tekstaro/tekstaro_release
    path: ./
    registry: hub.docker.com

workflows:
  test-and-deploy:
    jobs:
      - build_and_push
