version: 2.1

orbs:
  docker: circleci/docker@1.0.1

jobs:
  build:
    docker:
      - image: circleci/elixir:1.9.4
        environment:
          MIX_ENV: prod
    steps:
      - setup_remote_docker
      - checkout
      - docker/build:
          dockerfile: docker/aws.dockerfile
          image: iocarney/tekstaro_aws
          path: ./
      - docker/publish:
          image: tekstaro/tekstaro_aws
